[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/invoices"
  to = "/.netlify/functions/saveInvoice"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/invoices/:id"
  to = "/.netlify/functions/getInvoice"
  status = 200
  method = "GET"
